cve: adding CVE-2022-29458
canonical/notebook-operators pull request #258
Opened 2023-07-06 18:36 UTC by i-chvets

# Description

Adding CVE record.

2023-07-06 19:00 UTC, eslerm requested changes

2023-07-06 19:03 UTC, i-chvets commented on security/active/CVE-2022-29458
> +https://git.launchpad.net/ubuntu-cve-tracker/tree/retired/CVE-2022-29458
Should I just put it like this?
```
Notes-Kubeflow:
 i-chvets> Compromised package libncursesw6 is not used by Jupyter Web UI component.
 i-chvets> Not exploitable from frontend. Ignoring.
 i-chvets> https://git.launchpad.net/ubuntu-cve-tracker/tree/retired/CVE-2022-29458
```

2023-07-06 19:21 UTC, eslerm commented on security/active/CVE-2022-29458
> +https://git.launchpad.net/ubuntu-cve-tracker/tree/retired/CVE-2022-29458
I'd use
```
Notes-Kubeflow:
 i-chvets> Compromised package libncursesw6 is not used by Jupyter Web UI component.
 i-chvets> Not exploitable from frontend. Ignoring.
Referencess-Kubeflow:
 https://git.launchpad.net/ubuntu-cve-tracker/tree/retired/CVE-2022-29458
```
like https://git.launchpad.net/ubuntu-cve-tracker/tree/retired/CVE-2022-29458

It's your preference how notes are used though. In UCT, if I wanted to know who added a reference I'd `git blame`.

2025-01-20 15:16 UTC, orfeas-k commented
Closing as stale

2025-01-20 15:16 UTC, closed without merging