Update observability integration
canonical/notebook-operators pull request #33
Opened 2022-03-31 13:54 UTC by agathanatasha

Observability updates:
- rename interfaces
- use scrape charm
- hard code metrics config
- add basic alert rule
- add test

Others:
- remove controller's test-requirements.txt as all deps needed are already listed for each env
- update other test-requirements.txt to use latest black

2022-04-01 19:03 UTC, mmanciop requested changes

2022-04-01 19:03 UTC, mmanciop commented on charms/jupyter-controller/src/prometheus_alert_rules/unit_unavailable.rule
> +alert: EnvoyUnitIsUnavailable
Copy&paste mistake in alert name

2022-04-14 15:04 UTC, ca-scribner approved these changes

2022-04-29 15:28 UTC, ca-scribner approved these changes

2022-04-29 15:29 UTC, merged